# Generated by Django 5.1.7 on 2025-03-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_manufacturer', models.CharField(max_length=100)),
                ('asset_model', models.CharField(max_length=100)),
                ('asset_sn', models.CharField(max_length=50)),
                ('asset_cost', models.CharField(max_length=7)),
            ],
        ),
    ]
