# Generated by Django 5.1.7 on 2025-04-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_eolDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_purchaseDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_manufacturer',
            field=models.CharField(help_text='The manufacturer of the asset e.g. Dell, HP.', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_model',
            field=models.CharField(help_text='The model of the asset e.g. R740.', max_length=100),
        ),
    ]
