# Generated by Django 5.1.7 on 2025-04-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_asset_eoldate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_eolDate',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_purchaseDate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
