# Generated by Django 5.1.7 on 2025-04-12 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_asset_asset_eoldate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_cost',
            field=models.CharField(help_text='Enter the cost of the hardware. Do not include any associated services.', max_length=7),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_eolDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 12, 17, 27, 55, 657543)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_purchaseDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 12, 17, 27, 55, 657529)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_sn',
            field=models.CharField(help_text='Enter the serial number assigned by the manufacturer.', max_length=50),
        ),
    ]
