# Generated by Django 5.1.7 on 2025-04-13 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_asset_asset_eoldate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_eolDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 12, 21, 22, 16, 150257)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_purchaseDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 12, 21, 22, 16, 150242)),
        ),
    ]
