# Generated by Django 5.1.7 on 2025-04-13 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_alter_asset_asset_eoldate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_eolDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 12, 22, 3, 39, 646979)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_purchaseDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 12, 22, 3, 39, 646962)),
        ),
    ]
