# Generated by Django 5.1.7 on 2025-03-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maint_title', models.CharField(max_length=100)),
                ('maint_cost', models.CharField(max_length=7)),
            ],
        ),
    ]
