# Generated by Django 5.1.7 on 2025-04-13 01:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_alter_asset_asset_eoldate_and_more'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maint_assetID',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maint_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 21, 59, 37, 895583)),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maint_description',
            field=models.TextField(blank=True),
        ),
    ]
