# Generated by Django 5.1.7 on 2025-04-13 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenance_maint_assetid_maintenance_maint_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maint_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 22, 3, 39, 665965)),
        ),
    ]
