# Generated by Django 5.1.7 on 2025-04-15 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenance_maint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maint_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 6, 57, 36, 252113)),
        ),
    ]
