# Generated by Django 5.1.7 on 2025-04-18 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenance_maint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maint_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 11, 29, 12, 503197)),
        ),
    ]
