# Generated by Django 5.1.7 on 2025-04-26 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_maintenance_maint_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='maint_assetID',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='maint_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='maint_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='maint_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='maint_date',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 20, 8, 2, 513759)),
        ),
    ]
