# Generated by Django 5.1.7 on 2025-04-26 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_rename_maint_assetid_maintenance_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 20, 13, 27, 685070)),
        ),
    ]
