# Generated by Django 5.1.7 on 2025-04-26 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_maintenance_cost_alter_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 11, 56, 3, 662425)),
        ),
    ]
